### PR TITLE
[FYI, do not merge] Quickfix for pytest v8

### PR DESCRIPTION
**Pull request by jrapin**
This is an initial hack for updating pytest-markdown-docs to pytest v8. It's probably not fool-proof but at least it works for my use case.

**Issue:** pytest-markdown-docs fails on new pytest v8 (initially `TypeError: FixtureManager.getfixtureinfo() got an unexpected keyword argument 'funcargs'` but that's hiding a couple more changes)

See API changes from [v7](https://docs.pytest.org/en/7.1.x/_modules/_pytest/fixtures.html) to [v8](https://docs.pytest.org/en/8.0.x/_modules/_pytest/fixtures.html) in particular for `getfixtureinfo` and `FixtureRequest` becoming abstract.

### CODE REVIEW

**Comment by ekzhang** [comment]
How does it look @freider? I'm not familiar with this part of pytest internals

**Comment by freider** [comment]
Thanks for the contribution! I haven't had a chance to look at pytest 8 yet, but I just tried running the tests off this branch and it seems a couple are still failing. I'll see if I can make some fixes.

I'm also not very familiar with pytest internals (even before pytest 8) so it's been a bit of "patch it til' it works". One of these days I should do a read-through of pytest to gain a better understanding so this plugin can be cleaned up (contributions that clean up stuf are also very welcome!).

Should add some basic CI for this repo too now that I think of it

**Comment by freider** [comment]
Added a couple of additional commits to fix the broken tests and make the change compatible with both pytest 7 and 8, hope you don't mind (I actually had no idea that I could push to a branch of a fork of my repo that's not under my user/org on github).
Will try to set up some CI now and then push out a new release

**Comment by jrapin** [comment]
> Added a couple of additional commits to fix the broken tests and make the change compatible with both pytest 7 and 8!
Thanks a lot!

> hope you don't mind (I actually had no idea that I could push to a branch of a fork of my repo that's not under my user/org on github)
I don't mind at all, quite the opposite, happy you were able to take over

> Will try to set up some CI now and then push out a new release
Thank you!

**Pull request merged**
